-- 1. 사용자 테이블 생성
CREATE TABLE user (
  user_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  nickname VARCHAR(255) NOT NULL,
  birthdate DATE NOT NULL,
  phone_number VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  profile_image VARCHAR(255) NOT NULL,
  spec_level INT NOT NULL,
  manner_level INT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 2. 약관 테이블 생성
CREATE TABLE term (
  term_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  is_required BOOLEAN NOT NULL,
  term_version INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 3. 지역 테이블 생성
CREATE TABLE area (
  area_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  location POINT NOT NULL,
  legal_areacode VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 4. 스펙 테이블 생성
CREATE TABLE spec (
  spec_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 5. 이메일 인증 코드 테이블 생성
CREATE TABLE email_verification_code (
  email_verification_code_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) NOT NULL,
  code VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 6. 캘린더 테이블 생성
CREATE TABLE calendar (
  calendar_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 7. 대회 테이블 생성
CREATE TABLE contest (
  contest_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  host VARCHAR(255) NOT NULL,
  location POINT NOT NULL,
  online_offline_type VARCHAR(50) NOT NULL,
  application_start_date DATETIME NOT NULL,
  application_end_date DATETIME NOT NULL,
  start_date DATETIME NOT NULL,
  end_date DATETIME NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 8. 스터디룸 화상통화 테이블 생성
CREATE TABLE studyroom_videocall (
  studyroom_videocall_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL
);

-- 9. 사용자 약관 동의 테이블 생성
CREATE TABLE user_term (
  user_term_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  term_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  is_agreed BOOLEAN NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (term_id) REFERENCES term(term_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 10. 사용자 스펙 테이블 생성
CREATE TABLE user_spec (
  user_spec_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL,
  spec_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (spec_id) REFERENCES spec(spec_id)
);

-- 11. 사용자 지역 테이블 생성
CREATE TABLE user_area (
  user_area_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL,
  area_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (area_id) REFERENCES area(area_id)
);

-- 12. 사용자 OAuth 테이블 생성
CREATE TABLE user_oauth (
  user_oauth_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL,
  oauth_type VARCHAR(50) NOT NULL,
  oauth_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 13. 사용자 인증 이메일 테이블 생성
CREATE TABLE user_verified_email (
  user_verified_email_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL,
  verified_email VARCHAR(255) NOT NULL,
  verification_type VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 14. 사용자 리프레시 토큰 테이블 생성
CREATE TABLE user_refresh_token (
  user_refresh_token_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL,
  refresh_token TEXT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 15. 스터디룸 테이블 생성
CREATE TABLE studyroom (
  studyroom_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NOT NULL,
  area_id BIGINT NOT NULL,
  profile_image VARCHAR(255) NOT NULL,
  target_type VARCHAR(50) NOT NULL,
  target_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (area_id) REFERENCES area(area_id)
);

-- 16. 사용자 스터디룸 테이블 생성
CREATE TABLE user_studyroom (
  user_studyroom_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  studyroom_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (studyroom_id) REFERENCES studyroom(studyroom_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 17. 스터디룸 멤버 테이블 생성
CREATE TABLE studyroom_member (
  studyroom_member_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  studyroom_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(50) NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (studyroom_id) REFERENCES studyroom(studyroom_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 18. 스터디룸 캘린더 테이블 생성
CREATE TABLE studyroom_calendar (
  studyroom_calendar_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  studyroom_id BIGINT NOT NULL,
  calendar_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (studyroom_id) REFERENCES studyroom(studyroom_id),
  FOREIGN KEY (calendar_id) REFERENCES calendar(calendar_id)
);

-- 19. 스케줄 테이블 생성
CREATE TABLE schedule (
  schedule_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  calendar_id BIGINT NOT NULL,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME NOT NULL,
  location VARCHAR(255) NOT NULL,
  memo TEXT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (calendar_id) REFERENCES calendar(calendar_id)
);

-- 20. 스케줄 참가자 테이블 생성
CREATE TABLE schedule_participant (
  schedule_participant_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  schedule_id BIGINT NOT NULL,
  participant_id BIGINT NOT NULL,
  type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (schedule_id) REFERENCES schedule(schedule_id),
  FOREIGN KEY (participant_id) REFERENCES user(user_id)
);

-- 21. 대회 캘린더 테이블 생성
CREATE TABLE contest_calendar (
  contest_calendar_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  contest_id BIGINT NOT NULL,
  calendar_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (contest_id) REFERENCES contest(contest_id),
  FOREIGN KEY (calendar_id) REFERENCES calendar(calendar_id)
);

-- 22. 대회 스케줄 테이블 생성
CREATE TABLE contest_schedule (
  contest_schedule_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  contest_id BIGINT NOT NULL,
  schedule_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (contest_id) REFERENCES contest(contest_id),
  FOREIGN KEY (schedule_id) REFERENCES schedule(schedule_id)
);

-- 23. 사용자 캘린더 테이블 생성
CREATE TABLE user_calendar (
  user_id BIGINT NOT NULL,
  calendar_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (user_id, calendar_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id),
  FOREIGN KEY (calendar_id) REFERENCES calendar(calendar_id)
);

-- 24. 할 일 테이블 생성
CREATE TABLE todo (
  todo_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  deadline DATETIME NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  creater_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (creater_id) REFERENCES user(user_id)
);

-- 25. 스터디룸 할 일 테이블 생성
CREATE TABLE studyroom_todo (
  studyroom_todo_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  studyroom_id BIGINT NOT NULL,
  todo_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (studyroom_id) REFERENCES studyroom(studyroom_id),
  FOREIGN KEY (todo_id) REFERENCES todo(todo_id)
);

-- 26. 할 일 멤버 테이블 생성
CREATE TABLE todo_member (
  todo_member_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  todo_id BIGINT NOT NULL,
  assigned_user_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  comment TEXT NOT NULL,
  photo VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (todo_id) REFERENCES todo(todo_id),
  FOREIGN KEY (assigned_user_id) REFERENCES user(user_id)
);

-- 27. 대회 질문 테이블 생성
CREATE TABLE contest_question (
  contest_question_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  contest_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (contest_id) REFERENCES contest(contest_id),
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 28. 대회 답변 테이블 생성
CREATE TABLE contest_answer (
  contest_answer_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  contest_question_id BIGINT NOT NULL,
  answer_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (contest_question_id) REFERENCES contest_question(contest_question_id),
  FOREIGN KEY (answer_id) REFERENCES user(user_id)
);

-- 29. 게시판 테이블 생성
CREATE TABLE board (
  board_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  author BIGINT NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (author) REFERENCES user(user_id)
);

-- 30. 대회 게시판 테이블 생성
CREATE TABLE contest_board (
  contest_board_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  contest_id BIGINT NOT NULL,
  board_id BIGINT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (contest_id) REFERENCES contest(contest_id),
  FOREIGN KEY (board_id) REFERENCES board(board_id)
);

-- 31. 문의 테이블 생성
CREATE TABLE inquiry (
  inquiry_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  read_at DATETIME NOT NULL,
  answered_at DATETIME NOT NULL,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(user_id)
);

-- 32. 문의 답변 테이블 생성
CREATE TABLE inquiry_answer (
  inquiry_answer_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  inquiry_id BIGINT NOT NULL,
  admin_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (inquiry_id) REFERENCES inquiry(inquiry_id),
  FOREIGN KEY (admin_id) REFERENCES user(user_id)
);

-- 33. 스터디룸 화상통화 멤버 테이블 생성
CREATE TABLE studyroom_videocall_member (
  studyroom_videocall_member_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  studyroom_videocall_id BIGINT NOT NULL,
  member_id BIGINT NOT NULL,
  type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (studyroom_videocall_id) REFERENCES studyroom_videocall(studyroom_videocall_id),
  FOREIGN KEY (member_id) REFERENCES user(user_id)
);

-- 34. 스터디룸 채팅 테이블 생성
CREATE TABLE studyroom_chat (
  studyroom_chat_id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  sender_id BIGINT NOT NULL,
  studyroom_id BIGINT NOT NULL,
  type VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) NOT NULL,
  FOREIGN KEY (sender_id) REFERENCES user(user_id),
  FOREIGN KEY (studyroom_id) REFERENCES studyroom(studyroom_id)
);